name = "ernisto/rng"
version = "1.0.0-rc.1"
description = "a rng utility"
authors = ["ernisto <joaovitordesouza707@gmail.com>"]
repository = "https://github.com/ernisto/rng"
license = "MIT"

includes = [
    "pesde.toml",
    "README.md",
    "LICENSE",
    "lib/**",
    "docs/**/*.md",
]

[target]
environment = "luau"
lib = "lib/init.luau"

[engines]
pesde = "^0.7.1"

[indices]
default = "https://github.com/pesde-pkg/index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"
