name: Check

concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches-ignore: [master, dev]
  push:
    branches-ignore: [master, dev]

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your Git repo
        uses: actions/checkout@v2

      - name: Check Format
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ github.token }}
          version: 2.1.0
          args: --config-path stylua.toml --check lib tests

  lint-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your git repo
        uses: actions/checkout@v2

      - name: Setup rokit
        uses: CompeyDev/setup-rokit
        with:
          token: ${{ github.token }}

      - name: Lint
        run: >
          luau_lsp analyze
          --base-luaurc .luaurc
          --ignore **/luau_packages/**
          lib tests

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your Git repo
        uses: actions/checkout@v2

      - name: Setup Pesde Tools
        uses: axiom-co/setup-pesde@b690699ace34169731b6b2a1c93b2008472038a7

      - name: Run tests
        run: pesde x ernisto/test
