name: Release
on:
  release:

jobs:
  check:
    uses: ./.github/workflows/check.yml
    secrets: inherit

  deploy:
    runs-on: ubuntu-latest
    needs: [check]
    permissions:
      pull-requests: write
      contents: write
      issues: write
    steps:
      - name: Checkout git files
        uses: actions/checkout@v2

      - name: Setup rokit
        uses: CompeyDev/setup-rokit@v0.1.2
        with:
          token: ${{ github.token }}
  
      - name: Publish wally
        run: wally publish

      - name: Setup pesde
        uses: axiom-co/setup-pesde@b690699ace34169731b6b2a1c93b2008472038a7
        with:
          token: ${{ github.token }}

      - name: Publish pesde
        run: pesde publish -y

      - name: Release rbxm
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          rojo build default.project.json -o rng.rbxm
          gh release upload ${{github.event.release.tag_name}} rng.rbxm
