name: Release
on:
  workflow_dispatch:
  release:

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  check:
    uses: ./.github/workflows/check.yml
    secrets: inherit

  publish_npm:
    runs-on: ubuntu-latest
    needs: [check]
    steps:
      - uses: actions/checkout@v6
      - uses: CompeyDev/setup-rokit@v0.1.2
        with:
          token: ${{ github.token }}

      - name: Sync version
        run: lute run scripts/bump_version

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"

      - run: |
          VERSION=$(node -p "require('./package.json').version")
          TAG=latest

          if [[ "$VERSION" == *"-"* ]]; then
            TAG=$(echo "$VERSION" | cut -d'-' -f2 | cut -d'.' -f1)
          fi

          npm publish --access public --tag $TAG

  publish_wally:
    runs-on: ubuntu-latest
    needs: [check]
    steps:
      - uses: actions/checkout@v6
      - uses: CompeyDev/setup-rokit@v0.1.2
        with:
          token: ${{ github.token }}

      - name: Sync version
        run: lute run scripts/bump_version

      - run: wally login --token "${{ secrets.WALLY_TOKEN }}"
      - run: wally publish

  publish_pesde:
    runs-on: ubuntu-latest
    needs: [check]
    permissions:
      pull-requests: write
      contents: write
      issues: write
    steps:
      - uses: actions/checkout@v6
      - uses: CompeyDev/setup-rokit@v0.1.2
        with:
          token: ${{ github.token }}

      - name: Sync version
        run: lute run scripts/bump_version

      - uses: axiom-co/setup-pesde@b690699ace34169731b6b2a1c93b2008472038a7
        with:
          token: ${{ github.token }}

      - run: pesde auth login --token "${{ secrets.PESDE_AUTH }}"
      - run: pesde publish -y

  release_file:
    runs-on: ubuntu-latest
    needs: [check]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - uses: CompeyDev/setup-rokit@v0.1.2
        with:
          token: ${{ github.token }}

      - name: Build rbxm
        run: rojo build default.project.json -o rng.rbxm

      - name: Upload rbxm
        if: ${{github.event.release.tag_name}}
        run: gh release upload ${{github.event.release.tag_name}} rng.rbxm
        env:
          GH_TOKEN: ${{ github.token }}
